### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by soramico** [soramico/protospace-40946#1]
https://protospace-40946.onrender.com

**Comment by wad-sho** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正依頼箇所]**

- [x]  ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること

**現在は他のユーザーが投稿したプロトタイプの編集画面に入れてしまう状態です。**

【チェック方法】
先ず、ユーザーAで投稿したプロトタイプの編集ページURLをコピーします。
次にユーザーBでログインし、そのURLを直接入力した際に、トップページへリダイレクトされれば正常な挙動です。


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by wkn-a** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから編集ボタンをクリックすると、編集ページへ遷移できるようにしましょう。
 →現在、編集ボタンをクリックするとエラー画面に遷移してしまいます。

- [x] ログイン状態の投稿者だけが、自身の投稿したプロトタイプの詳細ページから削除ボタンをクリックすると、プロトタイプを削除できるようにしましょう。
→現在、削除ボタンをクリックするとエラー画面に遷移してしまいます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by shodai-ito** [comment]
@soramico さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
